"""Build a symlink overlay of the model directory with a TP-padded config.json.

vLLM derives every parallel layer's shape from the config, so the config has to
agree with what `glm53_tp_pad` does to the weight stream. Rather than
monkeypatching the config classes, we hand vLLM a directory that symlinks the
62 real shards (zero copy, no extra disk) and carries one rewritten file.

    python3 /opt/glm53/make_overlay.py --src /model --dst /model-tp6 --tp 6

`vocab_size` is deliberately left alone: the vocab is padded inside vLLM by
`pad_vocab_size`, and the lm_head/embed weights on disk still have 154880 rows.
Bumping it here would make vLLM expect rows the checkpoint does not have.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import glm53_tp_pad as pad  # noqa: E402

CONFIG_NAME = "config.json"


def _expect(container: dict, key: str, want: int, where: str) -> None:
    got = container.get(key)
    if got != want:
        raise SystemExit(
            f"[glm53-overlay] {where}.{key} is {got!r}, expected {want!r}. "
            "The checkpoint changed; re-check the constants in glm53_tp_pad.py "
            "against the new config.json before padding anything."
        )


def rewrite_config(config: dict, plan: pad.PadPlan) -> dict:
    text = config.get("text_config")
    if text is None:
        raise SystemExit("[glm53-overlay] config.json has no text_config")

    _expect(text, "num_attention_heads", pad.MLA_HEADS, "text_config")
    _expect(text, "index_n_heads", pad.IDX_HEADS, "text_config")
    _expect(text, "moe_intermediate_size", pad.MOE_INTERMEDIATE, "text_config")
    linear = text.get("linear_attn_config")
    if not isinstance(linear, dict):
        raise SystemExit("[glm53-overlay] text_config.linear_attn_config missing")
    _expect(linear, "num_heads", pad.KDA_HEADS, "linear_attn_config")

    changes = []

    def put(container, key, value, where):
        if container.get(key) != value:
            changes.append(f"{where}.{key}: {container.get(key)} -> {value}")
            container[key] = value

    if "mla" in plan.groups:
        put(text, "num_attention_heads", plan.mla_heads, "text_config")
        # MLA ignores this, but leaving it at 64 next to a 66-head config is a
        # trap for anyone reading the file later.
        if "num_key_value_heads" in text:
            put(text, "num_key_value_heads", plan.mla_heads, "text_config")
    if "indexer" in plan.groups:
        put(text, "index_n_heads", plan.idx_heads, "text_config")
    if "kda" in plan.groups:
        put(linear, "num_heads", plan.kda_heads, "linear_attn_config")
    if "moe" in plan.groups:
        put(text, "moe_intermediate_size", plan.moe_intermediate, "text_config")

    config.setdefault("_glm53_tp_pad", {})
    config["_glm53_tp_pad"] = {
        "tp": plan.tp,
        "groups": sorted(plan.groups),
        "changes": changes,
        "note": "generated by make_overlay.py; weights are padded at load time",
    }
    for change in changes:
        print(f"[glm53-overlay] {change}")
    if not changes:
        print("[glm53-overlay] config already matches the plan; nothing changed")
    return config


def build(src: str, dst: str, plan: pad.PadPlan) -> None:
    src = os.path.abspath(src)
    dst = os.path.abspath(dst)
    if not os.path.isdir(src):
        raise SystemExit(f"[glm53-overlay] source {src} is not a directory")
    if os.path.realpath(src) == os.path.realpath(dst):
        raise SystemExit("[glm53-overlay] refusing to overlay a directory onto itself")

    config_path = os.path.join(src, CONFIG_NAME)
    if not os.path.isfile(config_path):
        raise SystemExit(f"[glm53-overlay] {config_path} not found")
    with open(config_path, "r", encoding="utf-8") as handle:
        config = json.load(handle)
    config = rewrite_config(config, plan)

    # Rebuild from scratch so a restart cannot inherit a stale config.
    if os.path.islink(dst) or os.path.isfile(dst):
        os.unlink(dst)
    elif os.path.isdir(dst):
        shutil.rmtree(dst)
    os.makedirs(dst)

    linked = 0
    for entry in sorted(os.listdir(src)):
        if entry == CONFIG_NAME:
            continue
        os.symlink(os.path.join(src, entry), os.path.join(dst, entry))
        linked += 1

    with open(os.path.join(dst, CONFIG_NAME), "w", encoding="utf-8") as handle:
        json.dump(config, handle, indent=2)
        handle.write("\n")

    print(f"[glm53-overlay] {dst}: {linked} symlink(s) + rewritten {CONFIG_NAME}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", required=True, help="real model directory (read only)")
    parser.add_argument("--dst", required=True, help="overlay directory to create")
    parser.add_argument("--tp", type=int, required=True, help="tensor parallel size")
    parser.add_argument(
        "--groups",
        default=os.environ.get("GLM53_TP_PAD_GROUPS", ""),
        help="comma list from mla,kda,indexer,moe,vocab (default: all)",
    )
    args = parser.parse_args()

    groups = [g.strip() for g in args.groups.split(",") if g.strip()] or None
    plan = pad.plan_for_tp(args.tp, groups)
    if not plan.active:
        raise SystemExit(
            f"[glm53-overlay] TP={args.tp} needs no padding; serve /model directly"
        )
    print(f"[glm53-overlay] TP={plan.tp}: {plan.summary()}")
    build(args.src, args.dst, plan)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
